### ISSUE TITLE
HttpRequest

### ISSUE THREAD

**Issue by bataline** [alexanderkozlenko/aspnetcore-json-rpc#158]
Hi,

Is it possible somehow to retrieve System.Web.HttpRequest for each request?

I need IP address for each request.

**Comment by alexanderkozlenko** [comment]
Hi @bataline,

At the moment there is no ability to get the corresponding `Microsoft.AspNetCore.Http.HttpRequest` for the `JsonRpcRequest`. Is there anything specific in `HttpRequest`you need exactly in conjunction with `JsonRpcRequest`?

**Comment by bataline** [comment]
Hi @alexanderkozlenko,

Ouch, I've missed example with retrieving JsonRpcRequest.

But is it possible to get JsonRpcRequest when I use IJsonRpcService (and not IJsonRpcHandler)?
