### ISSUE TITLE
Automatic contract creation

### ISSUE THREAD

**Issue by ArmanHayots** [alexanderkozlenko/aspnetcore-json-rpc#8]
### Summary

Ability to use  `[JsonRpcMethod(autobind:true)]` to create contract based on method signature.

### Example

```
 [JsonRpcMethod("test", "b")]
public Task<int> Test(int b)
        {
            return Task.FromResult(b);
        }
```
can be replaced with something like
```
 [JsonRpcMethod(true)]
public Task<int> Test(int b)
        {
            return Task.FromResult(b);
        }
```

### Additional Information
 I'm actually don't know how to achieve this now, but if no one does maybe I will in the future.   
And of course it must understand that if method have only one `IEnumerable` arg, then it gonna bound to `params:[]`, not `params:{}`.

**Comment by alexanderkozlenko** [comment]
@ArmanHayots, thank you for the suggestion! Unfortunately, there are no plans at the moment to add support for automatic conventional contract creation based on type method names.
